server.port: 9090
spring:
  app:
    name: pocket-library-user

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/pocket_library
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PocketLibrary
